spring:
  application:
    name: yu-ai-code-mother-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/du_ai_code_mother
    username: root
    password: root
  profiles:
    active: dev

server:
  port: 8123
  servlet:
    context-path: /api

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: cn.huat.duaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn



