spring:
  application:
    name: du-ai-code-mother-backend
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/du_ai_code_mother
    username: root
    password: root
  profiles:
    active: dev
  # redis
  data:
    redis:
      host: 192.168.6.142
      port: 6379
      password: 123321
      ttl: 3600
      database: 13
  session:
    store-type: redis
    timeout: 2592000

server:
  port: 8123
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000

mybatis-flex:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: cn.huat.duaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn


# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: your-custom-domain.com
    secretId: your-secret-id
    secretKey: your-secret-key
    region: ap-shanghai
    bucket: your-bucket-name



